server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

loans:
  message: "Welcome to SquirtleBank loans related local APIs "
  contactDetails:
    name: "Rehan Sengupta - Developer"
    email: "rsengupta@squirtlebank.com"
  onCallSupport:
    - (111) 111-1234
    - (111) 123-1345